In [5]:
import plotly.express as px
import plotly.graph_objects as go
from shinywidgets import output_widget, render_widget, render_plotly
import pandas as pd

In [106]:
pop_size_instrument_df = pd.read_csv("/Users/poppyriddle/Documents/Github/ShinyShiny/dashboard-LNS/www/pop_size_instrument.csv", encoding="UTF-8")
pop_size_instrument_df.fillna(inplace=True,value=0)
pop_size_instrument_df

  Count of instrument_classified  ...  Test/task
0                  Not specified  ...        2.0
1                          1-100  ...        1.0
2                        100-500  ...        0.0
3                       500-1000  ...        1.0
4                      1000-5000  ...        0.0
5                     5000-10000  ...        0.0
6                         10000+  ...        0.0

[7 rows x 7 columns]

In [107]:
fig = px.bar(pop_size_instrument_df,
                y='Count of instrument_classified',
                x=['Interview/focus group',
                        'Other',
                        'Self-reported data',
                        'Standardized assessment/tool',
                        'Survey/questionnaire',
                        'Test/task'],
                #color_discrete_sequence=["red", "green", "blue", "goldenrod", "magenta","gray"],
                orientation='h',
                color_discrete_sequence= px.colors.sequential.Plotly3)
fig.update_layout(
        title="Population size by instrument",
        xaxis_title="Instrument",
        yaxis_title="Population size (participants)",
        height=400,
        width=600,
        )
fig

In [13]:
#a_time
a_time_df = pd.read_csv("www/a_time.csv", encoding="utf-8")
a_time_df

    year  Counts
0   2014      16
1   2015      13
2   2016      23
3   2017      14
4   2018      28
5   2019      19
6   2020      20
7   2021      14
8   2022      25
9   2023      17
10  2024       8

In [29]:
fig = px.bar(a_time_df, x='year', y='Counts',color='year',color_continuous_scale=px.colors.sequential.Plotly3)
fig.update_layout(
            title="Literature published over time",
            xaxis_title="Year",
            yaxis_title="Counts",
            
        )
fig

In [108]:
#plotly_a_funder_type
a_funder_type_df = pd.read_csv("www/a_funder_type.csv", encoding="UTF-8")
a_funder_type_df.fillna(inplace=True,value=0)
a_funder_type_df

            Literacy  ...  Nonprofit
0         Assessment  ...        0.0
1           Cultural  ...        0.0
2            Digital  ...        1.0
3   Essential skills  ...        0.0
4          Financial  ...        0.0
5             Health  ...        8.0
6        Ideological  ...        0.0
7        Information  ...        0.0
8           Language  ...        1.0
9               Math  ...        0.0
10             Media  ...        0.0
11    Multiliteracy   ...        0.0
12          Physical  ...        9.0
13        Scientific  ...        0.0
14       Traditional  ...        3.0

[15 rows x 7 columns]

In [109]:
fig = px.bar(a_funder_type_df,
        y='Literacy',
        x=['Academic institution/centre',
                'Corporation',
                'Government',
                'International organization',
                'No funding received or specified',
                'Nonprofit'],
        color_discrete_sequence= px.colors.sequential.Plotly3,
        orientation='h')
fig.update_layout(
                title="Funder by literacy type",
                xaxis_title="Literacy type",
                yaxis_title="Count of works",
                )
fig

In [104]:
#a_funder_concept
a_funder_concept_df = pd.read_csv("www/a_funder_concept.csv",encoding="UTF-8")
a_funder_concept_df.fillna(inplace=True,value=0)
a_funder_concept_df

    Concepts  ...  Nonprofit
0     Skills  ...          9
1      Mixed  ...         10
2  Practices  ...          3

[3 rows x 7 columns]

In [105]:
#a_funder_concept
fig = px.bar(a_funder_concept_df,
        x='Concepts',
        y=['Academic institution/centre',
            'Corporation',
            'Government',
            'International organization',
            'No funding received or specified',
            'Nonprofit'],
        color_discrete_sequence=px.colors.sequential.Plotly3,
        )
fig.update_layout(
            title="Literature published over time",
            xaxis_title="Year",
            yaxis_title="Counts",
            
        )
fig

In [50]:
#a_doc_type
a_doc_type_df = pd.read_csv("www/a_doc_type.csv", encoding="UTF-8")
a_doc_type_df

         Document type Location  Count
0       Article-Canada   Canada    130
1       Article-Global   Global     10
2        Report-Canada   Canada     26
3        Report-Global   Global      8
4  Web resource-Canada   Canada      3

In [52]:
import plotly.express as px
fig = px.pie(a_doc_type_df, values='Count',
            names='Document type',
            color_discrete_sequence=px.colors.sequential.Plotly3,
            hole=.4,
            facet_col='Location',
            title='Document types by geographic location')
fig.show()

In [68]:
#incicator concept
indicator_concept_df = pd.read_csv("www/indicator_concept.csv",encoding="UTF-8")
indicator_concept_df

         indicator    concept  count
0  Behaviour-based     Skills     18
1  Behaviour-based  Practices      5
2  Behaviour-based      Mixed     27
3       Contextual     Skills     17
4       Contextual  Practices      2
5       Contextual      Mixed      3
6     Skills-based     Skills    121
7     Skills-based  Practices      2
8     Skills-based      Mixed     36

In [73]:
fig = px.bar(indicator_concept_df,
            x='indicator',
            y='count',
            color='concept',
            color_discrete_sequence=px.colors.sequential.Plotly3_r)
fig.update_layout(
            title="Indicators and concepts",
            xaxis_title="Indicator",
            yaxis_title="Counts",
        )
fig

In [102]:
a_instrument_type_df = pd.read_csv("www/a_instrument_type.csv", encoding="UTF-8")
a_instrument_type_df.fillna(inplace=True,value=0)
a_instrument_concept_df

     concept  Interview/focus group  ...  Survey/questionnaire  Test/task
0  Practices                    0.0  ...                   0.0        0.0
1      Mixed                    1.0  ...                   5.0        0.0
2     Skills                   10.0  ...                  16.0        5.0

[3 rows x 7 columns]

In [103]:
fig = px.bar(a_instrument_type_df,
        y='instrument',
        x=['Interview/focus group',
                'Other',
                'Self-reported data',
                'Standardized assessment/tool',
                'Survey/questionnaire',
                'Test/task'],
        color_discrete_sequence= px.colors.sequential.Plotly3_r,
        orientation='h')
fig.update_layout(
                title="Count of instruments used by literacy type",
                xaxis_title="Count",
                yaxis_title="Literacy type",
                )
fig

In [100]:
a_instrument_concept_df = pd.read_csv("www/a_instrument_concept.csv", encoding="UTF-8")
a_instrument_concept_df.fillna(inplace=True,value=0)
a_instrument_concept_df

     concept  Interview/focus group  ...  Survey/questionnaire  Test/task
0  Practices                    0.0  ...                   0.0        0.0
1      Mixed                    1.0  ...                   5.0        0.0
2     Skills                   10.0  ...                  16.0        5.0

[3 rows x 7 columns]

In [101]:
fig = px.bar(a_instrument_concept_df,
        y='concept',
        x=['Interview/focus group',
                'Other',
                'Self-reported data',
                'Standardized assessment/tool',
                'Survey/questionnaire',
                'Test/task'],
        color_discrete_sequence= px.colors.sequential.Plotly3,
        orientation='h')
fig.update_layout(
                title="Count of concepts and instruments",
                xaxis_title="Count",
                yaxis_title="Conceptualization",
                )
fig

In [98]:
a_type_setting_df = pd.read_csv("www/a_type_setting.csv", encoding="UTF-8")
print(a_type_setting_df.columns)
a_type_setting_df.fillna(inplace=True,value=0)
a_type_setting_df

Index(['setting', 'Assessment', 'Cultural', 'Digital', 'Essential skills',
       'Financial', 'Health', 'Ideological', 'Information', 'Language', 'Math',
       'Media', 'Multiliteracy ', 'Physical', 'Scientific', 'Traditional'],
      dtype='object')

     setting  Assessment  Cultural  ...  Physical  Scientific  Traditional
0   Clinical         0.0       0.0  ...       2.0         0.0          0.0
1  Community         0.0       1.0  ...       9.0         2.0         14.0
2       Home         0.0       0.0  ...       1.0         0.0          5.0
3          0         0.0       0.0  ...       2.0         0.0          2.0
4     School         4.0       0.0  ...      25.0         6.0         20.0
5  Workplace         0.0       1.0  ...       0.0         1.0         30.0

[6 rows x 16 columns]

In [99]:
fig = px.bar(a_type_setting_df,
        y='setting',
        x=['Assessment', 'Cultural', 'Digital', 'Essential skills',
       'Financial', 'Health', 'Ideological', 'Information', 'Language', 'Math',
       'Media', 'Multiliteracy ', 'Physical', 'Scientific', 'Traditional'],
        color_discrete_sequence= px.colors.sequential.Plotly3,
        orientation='h')
fig.update_layout(
                title="Data collection setting by literacy type",
                xaxis_title="Count",
                yaxis_title="Setting",
                )
fig

In [116]:
raw_data_stats_df = pd.read_csv("www/raw_data_stats.csv",encoding="UTF-8")
count = raw_data_stats_df.iloc[3,1]
articles = raw_data_stats_df.iloc[0,1]
print(f"{count} Total\n{articles} Articles")

177 Total
140 Articles

In [145]:
geo_distribution_df = pd.read_csv("www/geo_distribution.csv", encoding="UTF-8")
geo_distribution_df

               location  count
0               Alberta      7
1      British Columbia     12
2              Manitoba      1
3         New Brunswick      1
4           Nova Scotia      1
5               Nunavut      2
6               Ontario     28
7  Prince Edward Island      1
8                Quebec      9
9          Saskatchewan      3

In [146]:
# plotly_geo_distribution
import plotly.express as px
fig = px.pie(geo_distribution_df, values='count',
            names='location',
            color_discrete_sequence=px.colors.sequential.Plotly3,
            hole=.4,
            #facet_col='location',
            title='Canadian works by location')
fig.show()

In [82]:
fig = px.colors.sequential.swatches()
fig.show()